# Raspberry Pi Cluster-Lab configuration management

**Work in progress!**

SD-Cards flashed by

[source,shell]
----
$ ./flash --hostname cl-leader https://downloads.hypriot.com/hypriotos-rpi-v0.8.0.img.zip
-----

Default user data

username: pirate
password: hypriot

## Scripts

The cluster-lab image does not have python installed, but it is needed by Ansible.

----
$ sh scripts/install_python.sh
----

## Playbooks

### network

Sets the IP address to a specific one.

[source,shell]
----
$ ansible-playbook network.yml --ask-pass
----

### Common

Do some common tasks like installations of tools and system configurations.

[source,shell]
----
$ ansible-playbook common.yml --ask-pass
----

## Ansible commands

### Stop cluster-lab on all nodes

[source,shell]
----
ansible cluster-nodes -b --become-method=sudo --user=pirate -a "cluster-lab stop"
----

### Troubleshooting

If you got an error like this one:

[source,shell]
----
$ docker info
An error occurred trying to connect: Get https://LEADER:2378/v1.23/info: tls: oversized record received with length 20527
----

Then unset this variable:

[source,shell]
----
unset DOCKER_TLS_VERIFY
----

#### Ubuntu to Debian comparison

|===
|Ubuntu number | Ubuntu name | Debian name

|16.04
|xenial
|stretch / sid

|15.10
|wily
|jessie  / sid

|15.04
|vivid
|jessie  / sid

|14.10
|utopic
|jessie  / sid

|14.04
|trusty
|jessie  / sid

|13.10
|saucy
|wheezy  / sid

|13.04
|raring
|wheezy  / sid

|12.10
|quantal
|wheezy  / sid

|12.04
|precise
|wheezy  / sid

|11.10
|oneiric
|wheezy  / sid

|11.04
|natty
|squeeze / sid

|10.10
|maverick
|squeeze / sid

|10.04
|lucid
|squeeze / sid
|===

http://askubuntu.com/questions/445487/which-ubuntu-version-is-equivalent-to-debian-squeeze[Source]
[# Raspberry pi cluster configuration management

### Docker-UI

https://github.com/kevana/ui-for-docker[Link to Docker-UI project]

#### Link to installed instance

[source,shell]
----
http://hostname:9000/
----

### Jenkins

#### Plugins

- https://github.com/jenkinsci/workflow-aggregator-plugin/tree/master/demo[workflow-aggregator]
- https://github.com/jenkinsci/docker-workflow-plugin[docker-workflow-plugin]
- git
- log-parser
- copyartifact
- workflow-multibranch
- template-project

## Helpful commands

### Log into running container

[source,shell]
----
docker exec -i -t CONTAINER_NAME_OR_ID /bin/bash
----

### Search for file content

[source,shell]
----
grep --color=auto -nsH 'CONTENT' *
----

