# Raspberry Pi 3 configuration management with Ansible

**Work in progress!**

## Flash SD Cards

Image: https://www.raspberrypi.org/downloads/[Raspbian]

Flash tool: https://github.com/hypriot/flash[Github hypriot/flash]

[source,shell]
----
$ curl -L https://downloads.raspberrypi.org/raspbian_lite_latest -o raspbian.zip
$ ./flash raspbian.zip
----

**Initial login data after boot**

username: pi
password: raspberry

## Playbooks

## network.yml

[source,shell]
----
$ ansible-playbook network.yml --ask-pass
----

Last task is rebooting the systems. The RPIs will be accessible by the new IP.

### common.yml

[source,shell]
----
$ ansible-playbook common.yml --ask-pass
----

### docker.yml

#### Docker-UI

https://github.com/kevana/ui-for-docker[Link to Docker-UI project]

#### Link to installed instance

[source,shell]
----
http://hostname:9000/
----

### jenkins.yml

## Helpful commands

### Log into running container

[source,shell]
----
docker exec -i -t CONTAINER_NAME_OR_ID /bin/bash
----

### Search for file content

[source,shell]
----
grep --color=auto -nsH 'CONTENT' *
----

### Find network addresses in the neighborhood

[source,shell]
----
arp -a -n
----

## Ubuntu to Debian comparison

|===
|Ubuntu number | Ubuntu name | Debian name

|16.04
|xenial
|stretch / sid

|15.10
|wily
|jessie  / sid

|15.04
|vivid
|jessie  / sid

|14.10
|utopic
|jessie  / sid

|14.04
|trusty
|jessie  / sid

|13.10
|saucy
|wheezy  / sid

|13.04
|raring
|wheezy  / sid

|12.10
|quantal
|wheezy  / sid

|12.04
|precise
|wheezy  / sid

|11.10
|oneiric
|wheezy  / sid

|11.04
|natty
|squeeze / sid

|10.10
|maverick
|squeeze / sid

|10.04
|lucid
|squeeze / sid
|===

http://askubuntu.com/questions/445487/which-ubuntu-version-is-equivalent-to-debian-squeeze[Source of table]


