#!/usr/bin/env bash
# {{ ansible_managed }}

export BASH_IT="/home/{{user_name}}/.bash_it"
export BASH_IT_THEME='bobby'
export GIT_HOSTING='git@github.com'
unset MAILCHECK
export SCM_CHECK=true

source $BASH_IT/bash_it.sh
